//AUTHENTICATION
export const ATTEMPT_AUTHENTICATION = 'ATTEMPT_AUTHENTICATION';
export const AUTHENTICATION_FAILIED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';

export const ATTEMPT_SIGNUP = 'ATTEMPT_SIGNUP';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const ATTEMPT_SIGNOUT = 'ATTEMPT_SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL';

//NOTIFICATION
export const OPEN_NOTIFICATION_BOX = 'OPEN_NOTIFICATION_BOX';
export const CLOSE_NOTIFICATION_BOX = 'CLOSE_NOTIFICATION_BOX';

//LOADER
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_PAGE_LOADER = 'SHOW_PAGE_LOADER'
export const HIDE_PAGE_LOADER = 'HIDE_PAGE_LOADER'

// USER TOPICS
export const ADD_NEW_TOPIC_INTEREST = 'ADD_NEW_TOPIC_INTEREST'
export const REMOVE_TOPIC_INTEREST = 'REMOVE_TOPIC_INTEREST'
export const ADD_TOPIC_INTEREST_SUCCESS = 'ADD_TOPIC_INTEREST_SUCCESS'
export const ADD_TOPIC_INTEREST_FAILED = 'ADD_TOPIC_INTEREST_FAILED'
export const USER_TOPICS_LOADED = "USER_TOPICS_LOADED"

// TOPICS 
export const LOAD_TOPICS = 'LOAD_TOPICS';
export const LOAD_TOPICS_SUCCESS = 'LOAD_TOPICS_SUCCESS';

// PROFILE
export const CHANGE_PROFILE_IMAGE = 'CHANGE_PROFILE_IMAGE'
export const CHANGE_PROFILE_NAME = 'CHANGE_PROFILE_NAME'

// BLOGS
export const LOAD_BLOGS = 'LOAD_BLOGS'
export const LOAD_BLOGS_SUCCESS = 'LOAD_BLOGS_SUCCESS'

// UI
export const OPEN_DASHBOARD_NAVIGATION = 'OPEN_DASHBOARD_NAVIGATION'
export const CLOSE_DASHBOARD_NAVIGATION = 'CLOSE_DASHBOARD_NAVIGATION'
export const TOGGLE_DASHBOARD_NAV = 'TOGGLE_DASHBOARD_NAV'

// timeline
export const LOAD_TIMELINE = 'LOAD_TIMELINE'